export interface SurahInfo {
  number: number
  name: string
  arabicName: string
  startPage: number
}

const RAW: SurahInfo[] = [
  { number: 1, name: 'Al-Fatiha', arabicName: 'الفاتحة', startPage: 1 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', startPage: 2 },
  { number: 3, name: 'Aal-i-Imran', arabicName: 'آل عمران', startPage: 50 },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', startPage: 77 },
  { number: 5, name: 'Al-Maidah', arabicName: 'المائدة', startPage: 106 },
  { number: 6, name: 'Al-An\'am', arabicName: 'الأنعام', startPage: 128 },
  { number: 7, name: 'Al-A\'raf', arabicName: 'الأعراف', startPage: 151 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', startPage: 177 },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', startPage: 187 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', startPage: 208 },
  { number: 11, name: 'Hud', arabicName: 'هود', startPage: 221 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', startPage: 235 },
  { number: 13, name: 'Ar-Ra\'d', arabicName: 'الرعد', startPage: 249 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', startPage: 255 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', startPage: 262 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', startPage: 267 },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', startPage: 282 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', startPage: 293 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', startPage: 305 },
  { number: 20, name: 'Ta-Ha', arabicName: 'طه', startPage: 312 },
  { number: 21, name: 'Al-Anbiya', arabicName: 'الأنبياء', startPage: 322 },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', startPage: 332 },
  { number: 23, name: 'Al-Mu\'minun', arabicName: 'المؤمنون', startPage: 342 },
  { number: 24, name: 'An-Nur', arabicName: 'النور', startPage: 350 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', startPage: 359 },
  { number: 26, name: 'Ash-Shu\'ara', arabicName: 'الشعراء', startPage: 367 },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', startPage: 377 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', startPage: 385 },
  { number: 29, name: 'Al-Ankabut', arabicName: 'العنكبوت', startPage: 396 },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', startPage: 404 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', startPage: 411 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', startPage: 415 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', startPage: 418 },
  { number: 34, name: 'Saba', arabicName: 'سبأ', startPage: 428 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', startPage: 434 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', startPage: 440 },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', startPage: 446 },
  { number: 38, name: 'Sad', arabicName: 'ص', startPage: 453 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', startPage: 458 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', startPage: 467 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', startPage: 477 },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', startPage: 483 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', startPage: 489 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', startPage: 496 },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', startPage: 499 },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', startPage: 502 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', startPage: 507 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', startPage: 511 },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', startPage: 515 },
  { number: 50, name: 'Qaf', arabicName: 'ق', startPage: 518 },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', startPage: 520 },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', startPage: 523 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', startPage: 526 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', startPage: 528 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', startPage: 531 },
  { number: 56, name: 'Al-Waqi\'ah', arabicName: 'الواقعة', startPage: 534 },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', startPage: 537 },
  { number: 58, name: 'Al-Mujadilah', arabicName: 'المجادلة', startPage: 542 },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', startPage: 545 },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', startPage: 549 },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', startPage: 551 },
  { number: 62, name: 'Al-Jumu\'ah', arabicName: 'الجمعة', startPage: 553 },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', startPage: 554 },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', startPage: 556 },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', startPage: 558 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', startPage: 560 },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', startPage: 562 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', startPage: 564 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', startPage: 566 },
  { number: 70, name: 'Al-Ma\'arij', arabicName: 'المعارج', startPage: 568 },
  { number: 71, name: 'Nuh', arabicName: 'نوح', startPage: 570 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', startPage: 572 },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', startPage: 574 },
  { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', startPage: 575 },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', startPage: 577 },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', startPage: 578 },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', startPage: 580 },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', startPage: 582 },
  { number: 79, name: 'An-Nazi\'at', arabicName: 'النازعات', startPage: 583 },
  { number: 80, name: 'Abasa', arabicName: 'عبس', startPage: 585 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', startPage: 586 },
  { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', startPage: 587 },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', startPage: 587 },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', startPage: 589 },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', startPage: 590 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', startPage: 591 },
  { number: 87, name: 'Al-A\'la', arabicName: 'الأعلى', startPage: 591 },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', startPage: 592 },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', startPage: 593 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', startPage: 594 },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', startPage: 595 },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', startPage: 595 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', startPage: 596 },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', startPage: 596 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', startPage: 597 },
  { number: 96, name: 'Al-Alaq', arabicName: 'العلق', startPage: 597 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', startPage: 598 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', startPage: 598 },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', startPage: 599 },
  { number: 100, name: 'Al-Adiyat', arabicName: 'العاديات', startPage: 599 },
  { number: 101, name: 'Al-Qari\'ah', arabicName: 'القارعة', startPage: 600 },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', startPage: 600 },
  { number: 103, name: 'Al-Asr', arabicName: 'العصر', startPage: 601 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', startPage: 601 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', startPage: 601 },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', startPage: 602 },
  { number: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', startPage: 602 },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', startPage: 602 },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', startPage: 603 },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', startPage: 603 },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', startPage: 603 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', startPage: 604 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', startPage: 604 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', startPage: 604 },
]

export interface SurahRange extends SurahInfo {
  endPage: number
}

export const SURAHS: SurahRange[] = RAW.map((s, i) => ({
  ...s,
  endPage:
    i === RAW.length - 1
      ? 604
      : Math.max(s.startPage, RAW[i + 1].startPage - 1),
}))
